site_name: PorriFPV
site_url: https://mydomain.org/mysite
theme:
  language: it
  logo: assets/logo.png
  name: material
  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode 
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    # - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share

plugins:
  - search
  - blog
  
nav:
  - MI PRESENTO: index.md
  - 3D:
    - BLENDER: 3D/BLENDER.md
  - CODE:
    - JAVA: CODE/IL-MIO-PRIMO-JAVA.md
  - I DRONI:
    - TRADIZIONALI: DRONI/TRADIZIONALI.md
    - FPV: DRONI/FPV.md
    - DIFFERENZE: DRONI/DIFFERENZE.md
  - PORTFOLIO:
    - PORTFOLIO: PORTFOLIO/PORTFOLIO.md
  - BLOG:
    -Primo Post: BLOG/Primo Post.md
    